# Generated by Django 4.1.6 on 2023-02-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_movie',
            name='img',
            field=models.ImageField(default='hjunb', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
